#version 460
#pragma shader_stage(compute)

layout(set = 0, binding = 0, rgba32f) uniform image2D i_Image;
layout(set = 0, binding = 1) uniform sampler2D i_Mask;

layout(push_constant) uniform PushConstants {
  uvec2 imageExtent; // 图像尺寸
  uvec2 maskExtent;  // 遮罩尺寸
} pc;

void main() {
  ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
  vec4 color = imageLoad(i_Image, coord);

  // 计算遮罩的中心偏移
  uvec2 maskOffset = (pc.imageExtent - pc.maskExtent) / 2;
  vec2 maskCoord = (vec2(coord) - vec2(maskOffset)) / vec2(pc.maskExtent);

  // 判断是否在遮罩区域内
  bool isMasked = coord.x >= maskOffset.x && coord.y >= maskOffset.y &&
                  coord.x < maskOffset.x + pc.maskExtent.x &&
                  coord.y < maskOffset.y + pc.maskExtent.y &&
                  texture(i_Mask, maskCoord).a > 0.5;

  if (isMasked) {
    imageStore(i_Image, coord, vec4(vec3(1.0f) - color.rgb, color.a));
  }
}
